"""Kokoro TTS for Bouriko. Produces WAV plus approximate word timings."""
import json, re
from pathlib import Path
from common import ROOT, CONFIG, log

def _load():
    from kokoro import KPipeline
    return KPipeline(lang_code=CONFIG.get("voices",{}).get("lang","a"))
def synthesize(text, voice, out):
    import soundfile as sf
    pipe=_load()
    chunks=[]
    for _,_,audio in pipe(text, voice=voice, speed=CONFIG.get("voices",{}).get("speed",1.05)):
        chunks.append(audio)
    if not chunks: raise RuntimeError("Kokoro returned no audio")
    import numpy as np
    audio=np.concatenate(chunks)
    sf.write(str(out),audio,24000)
    # Word timings are proportional to token count; exact lip sync is generated by Rhubarb later.
    words=re.findall(r"\S+",text)
    total=len(audio)/24000
    timings=[]; t=0
    for w in words:
        d=total*max(1,len(w))/max(1,sum(len(x) for x in words))
        timings.append({"word":w,"start":round(t,3),"end":round(t+d,3)}); t+=d
    return timings
def render_lines(story):
    od=ROOT/"output/audio"; od.mkdir(parents=True,exist_ok=True)
    all_words=[]; offset=0
    for i,line in enumerate(story["lines"]):
        voice=CONFIG["voices"]["bouriko"] if line["speaker"]=="BOURIKO" else CONFIG["voices"]["rock_phone"]
        wav=od/f"{i:02}.wav"; words=synthesize(line["text"],voice,wav)
        for w in words:
            w["line"]=i; w["start"]+=offset; w["end"]+=offset; all_words.append(w)
        import soundfile as sf
        offset+=len(sf.read(str(wav),always_2d=False)[0])/24000
    (ROOT/"output/word_timings.json").write_text(json.dumps(all_words,indent=2))
if __name__=="__main__":
    story=json.loads((ROOT/"output/story.json").read_text()); render_lines(story)
